---
title: "sankey-plot"
output:
  rmarkdown::html_vignette:
    fig_width: 5
    fig_height: 5
vignette: >
  %\VignetteIndexEntry{sankey-plot}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library("sankey")
```

```{r}
# Example data
strokedata <- read.csv(
  system.file("extdata", "strokedata.csv", package = "sankey")
)

# Scenario 1: With both horizontal and vertical white space
plot_sankey(strokedata,
            title = "Risk Factors for Stroke in Blacks",
            timeslope = 1, hspace = 0.03, vspace = TRUE)


# Scenario 2: With horizontal white space only
plot_sankey(strokedata,
            title = "Risk Factors for Stroke in Blacks",
            timeslope = 1, hspace = 0.03, vspace = FALSE)

# Scenario 3: With vertical white space only
plot_sankey(strokedata,
            title = "Risk Factors for Stroke in Blacks",
            timeslope = 1, hspace = 0, vspace = TRUE)

# Scenario 4: No horizontal and vertical white space
plot_sankey(strokedata,
            title = "Risk Factors for Stroke in Blacks",
            timeslope = 1, hspace = 0, vspace = FALSE)
```
